---
name: 'Run golangci-lint'
description: 'Official golangci-lint action with line-attached annotations for found issues, caching and parallel execution.'
author: 'golangci'
inputs:
  version:
    description: 'version of golangci-lint to use in form of v1.2.3'
    required: true
  args:
    description: 'golangci-lint command line arguments'
    default: ''
    required: false
  working-directory:
    description: 'golangci-lint working directory, default is project root'
    required: false
  github-token:
    description: 'the token is used for fetching patch of a pull request to show only new issues'
    default: ${{ github.token }}
    required: true
  only-new-issues:
    description: 'if set to true and the action runs on a pull request - the action outputs only newly found issues'
    default: false
    required: true

runs:
  using: 'node12'
  main: 'dist/run/index.js'
  post: 'dist/post_run/index.js'
branding:
  icon: 'shield'
  color: 'yellow'
